[package]
name = "formatonic"
version = "0.1.0"
authors = ["Yongshuo Chen <yongshuo4@gmail.com>"]
edition = "2024"
license = "MIT"
description = "A Rust drawing library focus on data parsing of ab init software"
repository = 


[dependencies]
pest = "2.5"
pest_derive = "2.5"