name: Report a bug
description: Any errors that are not UI related.
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: >
        Before you go any further.

        - Is this really a **bug**?
        - Is there any duplicated or similar issue?


  - type: textarea
    attributes:
      label: Bug description
      description: A description of the bug.
      placeholder: |
        A clear and concise description of what the bug is.

        Include steps to reproduce, the expected behaviour, and the actual behaviour.

        ```
        The error message you got, with the full traceback if available.
        ```

    validations:
      required: true

  - type: markdown
    attributes:
      value: "**Note: The rest of this form is optional, but filling it out may help us to provide better support.**"

  - type: textarea
    attributes:
      label: How to reproduce the bug
      description: >
        Provide steps and example code here.
      placeholder: |
        ```python
        # Sample code to reproduce the problem
        ```
      render: python
    validations:
      required: false

  - type: textarea
    attributes:
      label: Error messages and logs
      description: >
        Provide any error messages and/or logs
      placeholder: "# Copy the complete error messages and logs"
      value: |
        ```
        # Error messages and logs here please
        ```
    validations:
      required: false

  - type: textarea
    attributes:
      label: Environment
      description: |
        Please provide details about your environment

        You can also fill out the list below manually.
      value: |
        <details>
          <summary>Current environment</summary>

        ```
        #- OS (e.g., Linux):
        #- App version (e.g., 1.0)
        #- Python version (e.g., 3.9):
        ```

        </details>
    validations:
      required: false

  - type: textarea
    attributes:
      label: More info
      description: Add any other info about the issue here.
    validations:
      required: false

  - type: markdown
    attributes:
      value: "**Happy engineering!**"